In [1]:
%load_ext autoreload
%autoreload 2

import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from Utils.data_get_utils import get_duka_data_df
duka_5m_2020_df = get_duka_data_df("../data/EURUSD5_duka_2020.csv", "EURUSD")
duka_5m_2021_df = get_duka_data_df("../data/EURUSD5_duka_2021.csv", "EURUSD")
duka_5m_df = pd.concat([duka_5m_2020_df, duka_5m_2021_df])

duka_5m_df.head()

     symbol            datetime     open     high      low    close  volume
264  EURUSD 2020-01-01 22:00:00  1.12136  1.12139  1.12120  1.12125   47.60
265  EURUSD 2020-01-01 22:05:00  1.12125  1.12127  1.12125  1.12127   91.79
266  EURUSD 2020-01-01 22:10:00  1.12127  1.12127  1.12123  1.12127   64.98
267  EURUSD 2020-01-01 22:15:00  1.12127  1.12154  1.12127  1.12146   85.07
268  EURUSD 2020-01-01 22:20:00  1.12144  1.12153  1.12137  1.12146  123.93

In [3]:
from Utils.data_get_utils import get_fm_rc_data_df

rc_df = get_fm_rc_data_df("../data/yht_rc.csv")
rc_df[rc_df["date_var"]>=2].head()

,symbol,action,lots,open_date,close_date,open_price,close_price,profits,pips,commission,swaps,profits_calc,commission_by_pips,date_var,swap_by_time_variations_and_pips
97,GBPUSD,buy,0.01,2021-06-25 17:06:21,2021-06-28 03:47:47,1.38992,1.38874,-1.18,-11.8,-0.05,-0.03,-1.26,-0.5,3,-0.100000
146,XAUUSD,buy,0.01,2021-06-18 18:37:16,2021-06-20 22:03:35,1771.05000,1767.91000,-3.14,-31.4,-0.07,-0.05,-3.26,-0.7,2,-0.250000
147,XAUUSD,buy,0.01,2021-06-18 19:55:56,2021-06-20 22:02:37,1769.07000,1767.96000,-1.11,-11.1,-0.07,-0.05,-1.23,-0.7,2,-0.250000
366,XAUUSD,buy,0.01,2021-06-04 16:18:31,2021-06-07 13:12:48,1890.79000,1888.19000,-2.60,-26.0,-0.07,-0.05,-2.72,-0.7,3,-0.166667
367,XAUUSD,sell,0.01,2021-06-04 13:34:08,2021-06-07 02:57:50,1888.40000,1887.38000,1.02,10.2,-0.07,-0.04,0.91,-0.7,3,-0.133333

In [18]:
rc_df.columns

Index(['index', 'symbol', 'action', 'lots', 'open_date', 'close_date',
       'open_price', 'close_price', 'profits', 'pips', 'commission', 'swaps',
       'profits_calc', 'commission_by_pips', 'date_var',
       'swap_by_time_variations_and_pips', 'open_date_mod_5',
       'close_date_mod_5'],
      dtype='object')

In [4]:
from Utils.data_process_utils import get_period_bar_date
rc_df = get_period_bar_date(rc_df, ["open_date","close_date"], 5)
rc_df.head()

,symbol,action,lots,open_date,close_date,open_price,close_price,profits,pips,commission,swaps,profits_calc,commission_by_pips,date_var,swap_by_time_variations_and_pips,open_date_mod_5,close_date_mod_5
0,XAUUSD,sell,0.01,2021-07-09 15:14:50,2021-07-09 15:44:21,1808.27000,1808.19000,0.08,0.8,-0.07,0.0,0.01,-0.7,0,0.0,2021-07-09 15:10:00,2021-07-09 15:40:00
1,XAUUSD,sell,0.01,2021-07-09 15:01:27,2021-07-09 15:08:00,1807.84000,1807.72000,0.12,1.2,-0.07,0.0,0.05,-0.7,0,0.0,2021-07-09 15:00:00,2021-07-09 15:05:00
2,GBPUSD,sell,0.01,2021-07-09 14:20:29,2021-07-09 14:56:29,1.38567,1.38552,0.15,1.5,-0.05,0.0,0.10,-0.5,0,0.0,2021-07-09 14:20:00,2021-07-09 14:55:00
3,GBPUSD,sell,0.01,2021-07-09 14:35:57,2021-07-09 14:56:15,1.38636,1.38602,0.34,3.4,-0.05,0.0,0.29,-0.5,0,0.0,2021-07-09 14:35:00,2021-07-09 14:55:00
4,GBPUSD,sell,0.01,2021-07-09 14:38:30,2021-07-09 14:55:51,1.38672,1.38606,0.66,6.6,-0.05,0.0,0.61,-0.5,0,0.0,2021-07-09 14:35:00,2021-07-09 14:55:00

In [5]:
rc_df=rc_df[rc_df["symbol"]=="EURUSD"].reset_index()

### 检查是否交易记录是否在输入的EURUSD数据里面

In [6]:
%%time
# rc_df中的时间必须都在duka_5m_df当中存在
duka_5m_outer_join_rc_df = pd.merge(duka_5m_df, rc_df, left_on="datetime", right_on="open_date_mod_5", how="outer")
duka_5m_inner_join_rc_df = pd.merge(duka_5m_df, rc_df, left_on="datetime", right_on="open_date_mod_5", how="inner")
duka_5m_right_join_rc_df = pd.merge(duka_5m_df, rc_df, left_on="datetime", right_on="open_date_mod_5", how="right")
duka_5m_left_join_rc_df = pd.merge(duka_5m_df, rc_df, left_on="datetime", right_on="open_date_mod_5", how="left")
# duka_5m_left_join_rc_df = duka_5m_left_join_rc_df.dropna()

CPU times: user 38.8 ms, sys: 11.9 ms, total: 50.7 ms
Wall time: 50.5 ms

In [7]:
# classical methods to define the assert
assert len(duka_5m_left_join_rc_df.dropna()) == len(rc_df), (
        f'Some of the followme records are not in the instrument EURUSD input data.')
print(len(duka_5m_left_join_rc_df.dropna()))  
len(rc_df)

1890

1890

### 把时间周期关系全部搞清出来

In [8]:
# gmt + 8 == peking 
# gmt + 3 == tickmill

### 交易记录复现dataframe

In [9]:
print("bar data length:", len(duka_5m_df))

bar data length: 114042

In [10]:
duka_5m_df.head()

     symbol            datetime     open     high      low    close  volume
264  EURUSD 2020-01-01 22:00:00  1.12136  1.12139  1.12120  1.12125   47.60
265  EURUSD 2020-01-01 22:05:00  1.12125  1.12127  1.12125  1.12127   91.79
266  EURUSD 2020-01-01 22:10:00  1.12127  1.12127  1.12123  1.12127   64.98
267  EURUSD 2020-01-01 22:15:00  1.12127  1.12154  1.12127  1.12146   85.07
268  EURUSD 2020-01-01 22:20:00  1.12144  1.12153  1.12137  1.12146  123.93

In [11]:
rc_df.head()

,index,symbol,action,lots,open_date,close_date,open_price,close_price,profits,pips,commission,swaps,profits_calc,commission_by_pips,date_var,swap_by_time_variations_and_pips,open_date_mod_5,close_date_mod_5
0,10,EURUSD,buy,0.01,2021-07-09 02:05:44,2021-07-09 03:08:27,1.18363,1.18375,0.12,1.2,-0.04,0.0,0.08,-0.4,0,0.0,2021-07-09 02:05:00,2021-07-09 03:05:00
1,11,EURUSD,buy,0.01,2021-07-08 15:41:46,2021-07-08 15:52:30,1.18410,1.18440,0.30,3.0,-0.04,0.0,0.26,-0.4,0,0.0,2021-07-08 15:40:00,2021-07-08 15:50:00
2,12,EURUSD,sell,0.01,2021-07-08 13:55:29,2021-07-08 14:59:42,1.18600,1.18538,0.62,6.2,-0.05,0.0,0.57,-0.5,0,0.0,2021-07-08 13:55:00,2021-07-08 14:55:00
3,13,EURUSD,sell,0.01,2021-07-08 14:29:13,2021-07-08 14:48:43,1.18640,1.18613,0.27,2.7,-0.05,0.0,0.22,-0.5,0,0.0,2021-07-08 14:25:00,2021-07-08 14:45:00
4,14,EURUSD,sell,0.01,2021-07-08 13:32:00,2021-07-08 13:46:35,1.18589,1.18543,0.46,4.6,-0.05,0.0,0.41,-0.5,0,0.0,2021-07-08 13:30:00,2021-07-08 13:45:00

In [12]:
duka_5m_left_join_rc_df = pd.merge(duka_5m_df, rc_df, left_on="datetime", right_on="open_date", how="left")
assert len(duka_5m_left_join_rc_df) == len(duka_5m_df),(
    f'Some of the records data(rc_df) are not in the input bars(duka_5m_df) data'
)

In [13]:
duka_5m_left_join_rc_df.head()

,symbol_x,datetime,open,high,low,close,volume,index,symbol_y,action,...,profits,pips,commission,swaps,profits_calc,commission_by_pips,date_var,swap_by_time_variations_and_pips,open_date_mod_5,close_date_mod_5
0,EURUSD,2020-01-01 22:00:00,1.12136,1.12139,1.12120,1.12125,47.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
1,EURUSD,2020-01-01 22:05:00,1.12125,1.12127,1.12125,1.12127,91.79,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
2,EURUSD,2020-01-01 22:10:00,1.12127,1.12127,1.12123,1.12127,64.98,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
3,EURUSD,2020-01-01 22:15:00,1.12127,1.12154,1.12127,1.12146,85.07,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
4,EURUSD,2020-01-01 22:20:00,1.12144,1.12153,1.12137,1.12146,123.93,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT

In [14]:
from Utils.data_process_utils import slice_df_by_timerange
from datetime import timedelta

# rc_start_dt = duka_5m_left_join_rc_df.dropna()["open_date"].min() - timedelta(hours=2)
# rc_end_dt = duka_5m_left_join_rc_df.dropna()["close_date"].max() + timedelta(hours=2)
rc_start_dt = duka_5m_left_join_rc_df.dropna()["open_date"].min()
rc_end_dt = duka_5m_left_join_rc_df.dropna()["close_date"].max()
print("slicing date range : (", rc_start_dt, ", ", rc_end_dt, ")")
duka_5m_left_join_rc_date_filtered_df = slice_df_by_timerange(duka_5m_left_join_rc_df, "datetime", rc_start_dt, rc_end_dt)
analysis_df = duka_5m_left_join_rc_date_filtered_df.reset_index(drop=True)
analysis_df.head()

slicing date range : ( 2020-10-20 10:45:00 ,  2021-06-21 14:59:03 )

,symbol_x,datetime,open,high,low,close,volume,index,symbol_y,action,...,profits,pips,commission,swaps,profits_calc,commission_by_pips,date_var,swap_by_time_variations_and_pips,open_date_mod_5,close_date_mod_5
0,EURUSD,2020-10-20 10:45:00,1.18161,1.18173,1.18136,1.18154,3591.16,4918.0,EURUSD,sell,...,0.51,5.1,-0.04,0.0,0.47,-0.4,0.0,0.0,2020-10-20 10:45:00,2020-10-20 10:50:00
1,EURUSD,2020-10-20 10:50:00,1.18155,1.18158,1.18107,1.18108,3655.19,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
2,EURUSD,2020-10-20 10:55:00,1.18107,1.18142,1.18098,1.18135,2275.08,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
3,EURUSD,2020-10-20 11:00:00,1.18136,1.18154,1.18120,1.18121,2940.59,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
4,EURUSD,2020-10-20 11:05:00,1.18120,1.18137,1.18114,1.18131,2850.48,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT

In [15]:
len(analysis_df)

49686

In [19]:
from pandas.testing import assert_series_equal
import numpy as np
from numpy.testing import assert_array_almost_equal

trading_rc_columns = ['symbol', 'action', 'lots', 'open_date', 'close_date', 
                      'open_price', 'close_price', 'profits', 'pips', "commission", "swaps", 
                      'profits_calc', 'commission_by_pips', 'date_var',
                       'swap_by_time_variations_and_pips', 
                      'open_date_mod_5', 'close_date_mod_5']
cur_rc_df = pd.DataFrame(columns=trading_rc_columns)

cur_rc_df.head()

commisions counted by pips:  [-0.4        -0.5        -0.45       -0.46666667 -0.46363636 -0.475
 -0.46       -0.43333333 -0.46153846 -0.46923077 -0.46875    -0.46428571
 -0.47       -0.465      -0.45454545 -0.458      -0.44      ]

,symbol,action,lots,open_date,close_date,open_price,close_price,profits,pips,commission,swaps,profits_calc,commission_by_pips,date_var,swap_by_time_variations_and_pips,open_date_mod_5,close_date_mod_5
0,EURUSD,buy,0.01,2021-07-09 02:05:44,2021-07-09 03:08:27,1.18363,1.18375,0.12,1.2,-0.04,0.0,0.08,-0.4,0,0.0,2021-07-09 02:05:00,2021-07-09 03:05:00
1,EURUSD,buy,0.01,2021-07-08 15:41:46,2021-07-08 15:52:30,1.18410,1.18440,0.30,3.0,-0.04,0.0,0.26,-0.4,0,0.0,2021-07-08 15:40:00,2021-07-08 15:50:00
2,EURUSD,sell,0.01,2021-07-08 13:55:29,2021-07-08 14:59:42,1.18600,1.18538,0.62,6.2,-0.05,0.0,0.57,-0.5,0,0.0,2021-07-08 13:55:00,2021-07-08 14:55:00
3,EURUSD,sell,0.01,2021-07-08 14:29:13,2021-07-08 14:48:43,1.18640,1.18613,0.27,2.7,-0.05,0.0,0.22,-0.5,0,0.0,2021-07-08 14:25:00,2021-07-08 14:45:00
4,EURUSD,sell,0.01,2021-07-08 13:32:00,2021-07-08 13:46:35,1.18589,1.18543,0.46,4.6,-0.05,0.0,0.41,-0.5,0,0.0,2021-07-08 13:30:00,2021-07-08 13:45:00

In [17]:
%%time
trading_rc_columns = ['symbol_y', 'action', 'lots', 'open_date', 'close_date', 
                                  'open_price', 'close_price', 'profits', 'pips', 
                                  'open_date_mod_5', 'close_date_mod_5']
cur_rc_df = pd.DataFrame(columns=trading_rc_columns)
# for idx,row in analysis_df.iterrows():
    # maintain a dataframe to save the order data
    # records the closing_net_equity(平仓净值) and floating_net_equity(持仓净值)
#     cur_rc_df.columns = ['symbol_y', 'action', 'lots', 'open_date', 'close_date', 
#                          'open_price', 'close_price', 'profits', 'pips', 
#                          'open_date_mod_5', 'close_date_mod_5']
    
cur_rc_df.columns

CPU times: user 740 µs, sys: 61 µs, total: 801 µs
Wall time: 796 µs

Index(['symbol_y', 'action', 'lots', 'open_date', 'close_date', 'open_price',
       'close_price', 'profits', 'pips', 'open_date_mod_5',
       'close_date_mod_5'],
      dtype='object')